<?php
/**
 * Created by PhpStorm.
 * User: 김종갑
 * Date: 2017-02-22
 * Time: 오전 10:07
 */

namespace App\Model;

class NoticeModel {

    public function __construct($db, $logger){
        parent::__construct($db, $logger);
    }

    public function getLists(){

    }

    public function __destruct(){
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

}